apiVersion: template.openshift.io/v1
kind: Template
labels:
    template: pipeline
metadata:
  annotations:
    description: RHTE CICD Deployment Pipeline
  name: pipeline
parameters:
- name: GIT_REPO
  value: https://github.com/myeung18/IntegrationApp-Automation.git
  required: false
- name: GIT_BRANCH
  value: 3scalepublish 
  required: false
- name: MYSQL_USER 
  value: dbuser 
  required: false
- name: MYSQL_PWD
  value: password 
  required: false
- name: API_TOKEN
  displayName: Access token from 3scale 
  required: true
  value: a96c1296376a4901d90d69405265843b888b12649e827052fe67dcdb899c4c61
  description: Access token from 3scale for calling management API
- name: THREESCALE_URL
  displayName: Admin URL of Threescale
  required: true
  value: https://3scale-admin.app.rhdp.ocp.cloud.lab.eng.bos.redhat.com
  description: Admin URL of Threescale
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: 3scale-publishing-pipeline
    labels:
      app: 3scale-publishing-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: Git 
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile3scale
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: MYSQL_USER 
          value: ${MYSQL_USER}
        - name: MYSQL_PWD 
          value: ${MYSQL_PWD}
        - name: API_TOKEN
          value: ${API_TOKEN}
        - name: THREESCALE_URL
          value: ${THREESCALE_URL}
